dist: xenial
language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
matrix:
  fast_finish: true
before_install:
- sudo apt-get -qq update
install:
- pip install -U pip
- pip install -U setuptools
- pip install tox-travis codecov
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: benmaddison
  distributions: sdist bdist_wheel
  password:
    secure: rOwpfTcx+1Sp0piFKKzw+uW311Qy1Cz5Lv95KXAv66qDU0yrOdkd4Y9PFr7yozmidaAw97zDWpyhcQ++xbeWpbgKfAi/Bvbh9FACCkMeB/srBPvGVmWDhL/Cv/hO9k8UgKanHWNs1IYWfFsKzwlPpz2qNN64/W6wl0b7ho18UxSpybBUbezw+zsZQD4GPhnHePGO4hZLysMO40EzS5cP96XQqmeReOv4M4HeeMWGh3fLgHgv8eOfxls/aBuL7k6UCYXdKcc62KHtoTJXWQkaSfYAoRZO5KyTxKTSDOTmSZ1C+Kl6RYyD7RoYWm4c4LHBkCB5G+S/ifof3DVc4Lnpidr8jbMGkwnCCWm5AZxg/q4TLejLUwMzdAbm8BtlyOfZOMuCz0wt+HnZWnUbYLlPJ6i31eHpWkaxWjjh7Xy34zrE6n4YQfJhegZ/gBzy547q5GDRS5M8516XHz2wTue43TVQRcY3A0rF1K4lSqMwr6tKzArMVaTyYscr6kmSjqLJgv8tq+sFnctAeOJRxG80KhCp4odi51TP91OG9K5WnqjvIcT1rIwu546Wzg5JQyllSYjR3K26z99Dk7wc2COSrNJ9vndrVWbSPSXNpC/JAF4mBUAjWUvurEqa2xRb21bfbtC7Vzg3HAWQqtwCsZ3rCw6mFHNfi9d7dmda56hRv8A=
  on:
    tags: true
    python: '3.6'
